create table "public"."temp" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."temp" enable row level security;

CREATE UNIQUE INDEX temp_pkey ON public.temp USING btree (id);

alter table "public"."temp" add constraint "temp_pkey" PRIMARY KEY using index "temp_pkey";


